---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by qufangliu.
--- DateTime: 2018/6/14 下午3:11
---

require("Thirdparty.FairyGUI")

UIPackage.AddPackage("UI/Demo")
local view = UIPackage.CreateObject("Demo", "start")
GRoot.inst:AddChild(view)